inherit_from: .rubocop_todo.yml

require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec

AllCops:
  NewCops: enable
  Exclude:
    - 'bin/*'
    - 'db/**/*'
    - 'tmp/**/*'
    - 'vendor/**/*'
    - 'app/controllers/recipes_controller.rb'
  TargetRubyVersion: 3.1

Metrics/BlockLength:
  Max: 30
  Exclude:
    - 'config/environments/development.rb'
